globalvar grid_index;
globalvar grid_info;
globalvar planet_info;
globalvar current_grid;
globalvar fuel;
globalvar air;
globalvar water;
globalvar food;
globalvar gameover;
globalvar canmove;
globalvar current_stars;
globalvar current_planets;
globalvar current_asteroids;
globalvar current_moons;
globalvar current_celestial_bodies;
globalvar planet_id;
globalvar planet_info;
globalvar passengers;
globalvar communicationFound;

grid_index = 0;
fuel = 5000;
air = 5000;
water = 5000;
food = 5000;
gameover = 0;
canmove = 1;
planet_id = 0;
passengers = 5;
communicationFound = 0;
